// test/fixtures.js
export const sampleClasses = [
  "m-5",
  "p-2",
  "-m-2",
  "!m-32px",
  "hover:bg-blue-500",
  "md:flex",
  "dark:md:hover:bg-red-300/30",
  "object-contain",
  "of-cover",
  "!of-cover",
  "ov-hidden",
  "!of-contain",
  "!ov-x-hidden",
  "ov-auto",

  "hue-rotate-45",
  "-hue-rotate-45",
  "hue-rotate-45deg",
  "-hue-rotate-45deg",
  "hue-rotate-3/4turn",
  "-hue-rotate-1/4turn",

  "opacity-inherit",
  "opacity-initial",
  "opacity-revert",
  "opacity-unset",
  "opacity-50",

  "pattern-angle-50",
  "pattern-angle-50deg",
  "-pattern-angle-50deg",
  "!-pattern-angle-50deg",
  "pattern-angle-1/4",
  "pattern-angle-1/3turn",
  "-pattern-angle-1/3turn",

  "flex-row",
  "!flex-x",
  "fd-row",
  "fd-col",
  "fw-wrap",
];
